version: '3'

services:
  alpine-ftp-server:
    image: delfer/alpine-ftp-server
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    environment:
      - USERS=one|1234
      - ADDRESS=ftp.site.domain
    restart: always
